window.onload = function () {
  const dictionary = [
    {
      sentence: "",
      translation: "",
      audioLink: "",
      imagemLink: ""
    }
  ]



  let words = [
    'Ability',
    'Account',
    'Actor',
    'Address',
    'Adult',
    'Advice',
    'Affair',
    'Afternoon',
    'Age',
    'Air',
    'Airport',
    'Animal',
    'Apartment',
    'Apple',
    'Approach',
    'Area',
    'Arm',
    'Art',
    'Aunt',
    'Authority',
    'Award',
    'Awareness',
    'Baby',
    'Bag',
    'Ball',
    'Banana',
    'Bank',
    'Bath',
    'Bathroom',
    'Beach',
    'Beans',
    'Beauty',
    'Bed',
    'Bedroom',
    'Bee',
    'Beer',
    'Beginning ',
    'Behaviour',
    'Belt',
    'Bike',
    'Bill',
    'Bird',
    'Birthday',
    'Board',
    'Body',
    'Bone',
    'Book',
    'Bottle',
    'Bowl',
    'Box',
    'Boy',
    'Boyfriend',
    'Bread',
    'Break',
    'Breakfast',
    'Breath',
    'Bridge',
    'Brother',
    'Bus',
    'Butter',
    'Cafe',
    'Cake',
    'Camera',
    'Candy',
    'Cap',
    'Car',
    'Card',
    'Care',
    'Case',
    'Cat',
    'Chair',
    'Change',
    'Character',
    'Cheese',
    'Cherry',
    'Chicken',
    'Child',
    'Childhood',
    'Chips',
    'Chocolate',
    'Choice',
    'Church',
    'Circle',
    'Classroom',
    'Clothes',
    'Club',
    'Coffee',
    'College',
    'Color',
    'Company',
    'Competition',
    'Computer',
    'Conversation',
    'Cookies',
    'Couch',
    'Country',
    'Couple',
    'Course',
    'Cousin',
    'Crowd',
    'Culture',
    'Cup',
    'Customer',
    'Dad',
    'Darkness',
    'Date',
    'Daughter',
    'Day',
    'Death',
    'Design',
    'Desire',
    'Desk',
    'Dessert',
    'Dinner',
    'Doctor',
    'Dog',
    'Door',
    'Drawning',
    'Dream',
    'Dress',
    'Drink',
    'Driver',
    'Ear',
    'Earphone',
    'Earrings',
    'Earth',
    'East',
    'Economy',
    'Egg',
    'End',
    'Energy',
    'English',
    'Exercise',
    'Experience',
    'Eye',
    'Face',
    'Fact',
    'Faith',
    'Fall',
    'Family',
    'Fan',
    'Fashion',
    'Father',
    'Fear',
    'Figure',
    'File',
    'Film',
    'Fingers',
    'Fire',
    'Fish',
    'Floor',
    'Flower',
    'Food',
    'Football',
    'Fork',
    'Freedom',
    'Friday',
    'Friend',
    'Friendship',
    'Fruit',
    'Future',
    'Garden',
    'Gift',
    'Girl',
    'Girlfriend',
    'Glass',
    'Glasses',
    'Goal',
    'God',
    'Gold',
    'Grandfather',
    'Grandmother',
    'Grape',
    'Grass',
    'Grocery',
    'Group',
    'Guitar',
    'Guy',
    'Hair',
    'Hall',
    'Hand',
    'Hardware',
    'Hat',
    'Heart',
    'Heat',
    'Height',
    'Help',
    'Homework',
    'Honey',
    'Hope',
    'Hospital',
    'Hotel',
    'Hour',
    'House',
    'Husband',
    'Ice',
    'Ice cream',
    'Idea',
    'Imagination',
    'Information',
    'Insect',
    'Jacket',
    'Jam',
    'Job',
    'Juice',
    'Key',
    'Keyboard',
    'Keychain',
    'Kid',
    'Kitchen',
    'Knife',
    'Knowledge',
    'Lady',
    'Land',
    'Language',
    'Law',
    'Lawyer',
    'Leadership',
    'Left',
    'Leg',
    'Lemon',
    'Lemonade',
    'Letter',
    'Lettuce',
    'Library',
    'Life',
    'Light',
    'Line',
    'Lips',
    'Look',
    'Love',
    'Lunch',
    'Magazine',
    'Mail',
    'Mailman',
    'Mall',
    'Manager',
    'Market',
    'Marketing',
    'Marriage',
    'Material',
    'Maths',
    'Meat',
    'Meeting',
    'Memory',
    'Men',
    'Midnight',
    'Milk',
    'Mind',
    'Minute',
    'Mirror',
    'Mistake',
    'Mom',
    'Moment',
    'Monday',
    'Money',
    'Moon',
    'Morning',
    'Mother',
    'Mouse',
    'Mouth',
    'Movie',
    'Music',
    'Name',
    'Nature',
    'Need',
    'Neighbourhood',
    'Nephew',
    'News',
    'Niece',
    'Night',
    'North',
    'Nose',
    'Notebook',
    'Number',
    'Nurse',
    'Object',
    'Office',
    'Officer',
    'Opinion',
    'Orange',
    'Other',
    'Page',
    'Painting',
    'Pants',
    'Paper',
    'Parent',
    'Park',
    'Part',
    'Partner',
    'Passion',
    'Past',
    'Pasta',
    'Path',
    'Peace',
    'Pen',
    'Pencil',
    'People',
    'Pepper',
    'Period',
    'Person',
    'Photo',
    'Piano',
    'Picture',
    'Pie',
    'Pineapple',
    'Pizza',
    'Place',
    'Plant',
    'Plate',
    'Player',
    'Poem',
    'Poet',
    'Point',
    'Police officer',
    'Pork',
    'Potato',
    'Power',
    'Practice',
    'Present',
    'President',
    'Price',
    'Problem',
    'Professor',
    'Project',
    'Public',
    'Purpose',
    'Quality',
    'Rabbit',
    'Race',
    'Radio',
    'Reader',
    'Reason',
    'Recipe',
    'Record',
    'Reflection',
    'Refrigerator',
    'Relationship',
    'Research',
    'Restaurant',
    'Reunion',
    'Rice',
    'Right',
    'Rings',
    'Risk',
    'River',
    'Road',
    'Rock',
    'Romance',
    'Roof',
    'Room',
    'Rule',
    'Running',
    'Salad',
    'Salt',
    'Saturday',
    'School',
    'Science',
    'Screen',
    'Sea',
    'Season',
    'Secretary',
    'Sense',
    'Service',
    'Shelf',
    'Shirt',
    'Shoes',
    'Show',
    'Side',
    'Singer',
    'Sir',
    'Sister',
    'Skin',
    'Skirt',
    'Sky',
    'Smartphone',
    'Sneaker',
    'Soap',
    'Society',
    'Sofa',
    'Soft drink',
    'Software',
    'Solution',
    'Son',
    'Song',
    'Soup',
    'South',
    'Space',
    'Speaker',
    'Speech',
    'Spoon',
    'Spring',
    'Staff',
    'Stage',
    'Star',
    'Station',
    'Stock',
    'Storage',
    'Story',
    'Strategy',
    'Strawberry',
    'Street',
    'Stress',
    'Student',
    'Style',
    'Subject',
    'Subway',
    'Sugar',
    'Summer',
    'Sun',
    'Sunday',
    'Support',
    'Swimming',
    'Sympathy',
    'T-shirt',
    'Table',
    'Tale',
    'Talk',
    'Task',
    'Tea',
    'Teacher',
    'Team',
    'Technology',
    'Teenager',
    'Teeth',
    'Telephone',
    'Television',
    'Tennis shoes',
    'Test',
    'Text',
    'Thanks',
    'Theatre',
    'Theory',
    'Thing',
    'Thought',
    'Thursday',
    'Time',
    'Toast',
    'Today',
    'Tomorrow',
    'Tongue',
    'Tool',
    'Topic',
    'Touch',
    'Town',
    'Train',
    'Transport',
    'Travel',
    'Trouble',
    'Trousers',
    'Trunk',
    'Truth',
    'Tuesday',
    'Type',
    'Umbrella',
    'Uncle',
    'Understanding',
    'Underwear',
    'University',
    'Vegetables',
    'Vehicle',
    'Video',
    'View',
    'Voice',
    'Volleyball',
    'Volume',
    'Waiter',
    'Wallet',
    'Wardrobe',
    'Water',
    'Watermelon',
    'Way',
    'Weather',
    'Wednesday',
    'Week',
    'Weight',
    'West',
    'Wife',
    'Window',
    'Wine',
    'Winner',
    'Winter',
    'Woman',
    'Wood',
    'Word',
    'Work',
    'Worker',
    'World',
    'Wristwatch',
    'Writer',
    'Year',
    'Yesterday',
    'Youth',
    'Soccer',
    'History',
    'Business',
    'Service',
    'Building',
    'Smile',
    'Happiness',
  ];

  let translatedWords = [
    'Habilidade',
    'Relatório',
    'Ator',
    'Endereço',
    'Adulto',
    'Conselho',
    'Caso',
    'Tarde',
    'Idade',
    'Ar',
    'Aeroporto',
    'Animal',
    'Apartamento',
    'Maçã',
    'Aproximação',
    'Área',
    'Braço',
    'Arte',
    'Tia',
    'Autoridade',
    'Prêmio',
    'Consciência',
    'Bebê',
    'Bolsa',
    'Bola',
    'Banana',
    'Banco',
    'Banho',
    'Banheiro',
    'Praia',
    'Feijão',
    'Beleza',
    'Cama',
    'Quarto',
    'Abelha',
    'Cerveja',
    'Começo',
    'Comportamento',
    'Cinto',
    'Bicicleta',
    'Conta',
    'Pássaro',
    'Aniversário',
    'Quadro',
    'Corpo',
    'Osso',
    'Livro',
    'Garrafa',
    'Tigela',
    'Caixa',
    'Menino',
    'Namorado',
    'Pão',
    'Pausa',
    'Café da manhã',
    'Respiração',
    'Ponte',
    'Irmão',
    'Ônibus',
    'Manteiga',
    'Cafeteria',
    'Bolo',
    'Câmera',
    'Doce',
    'Boné',
    'Carro',
    'Cartão',
    'Cuidado',
    'Caso/capa protetora',
    'Gato',
    'Cadeira',
    'Mudança',
    'Personagem',
    'Queijo',
    'Cereja',
    'Frango',
    'Criança',
    'Infância',
    'Batata frita de pacote',
    'Chocolate',
    'Escolha',
    'Igreja',
    'Círculo',
    'Sala de aula',
    'Roupas',
    'Clube',
    'Café',
    'Faculdade',
    'Cor',
    'Empresa',
    'Competição',
    'Computador',
    'Conversa',
    'Biscoitos',
    'Sofá',
    'País',
    'Casal',
    'Curso',
    'Primo',
    'Multidão',
    'Cultura',
    'Copo',
    'Cliente',
    'Pai',
    'Escuridão',
    'Data/ Encontro',
    'Filha',
    'Dia',
    'Morte',
    'Design',
    'Desejo',
    'Mesa',
    'Sobremesa',
    'Janta',
    'Médico',
    'Cachorro',
    'Porta',
    'Desenho',
    'Sonho',
    'Vestido',
    'Bebida',
    'Motorista',
    'Orelha',
    'Fone de ouvido',
    'Brinco',
    'Terra',
    'Leste',
    'Economia',
    'Ovo',
    'Final',
    'Energia',
    'Inglês',
    'Exercício',
    'Experiência',
    'Olho',
    'Rosto',
    'Fato',
    'Fé',
    'Queda/ Outono',
    'Família',
    'Ventilador/fã',
    'Moda',
    'Pai',
    'Medo',
    'Figura/ Silhueta',
    'Arquivos',
    'Filme',
    'Dedos',
    'Fogo',
    'Peixe',
    'Chão/ Andar de prédio',
    'Flores',
    'Comida',
    'Futebol americano',
    'Garfo',
    'Liberdade',
    'Sexta-Feira',
    'Amigo',
    'Amizade',
    'Fruta',
    'Futuro',
    'Jardim',
    'Presente',
    'Menina',
    'Namorada',
    'Vidro',
    'Óculos',
    'Objetivo',
    'Deus',
    'Ouro',
    'Avô',
    'Avó',
    'Uvas',
    'Grama',
    'Compras de mercado',
    'Grupo',
    'Violão',
    'Garoto',
    'Cabelo',
    'Corretor',
    'Mão',
    'Hardware',
    'Chapéu',
    'Coração',
    'Calor/ Aquecedor',
    'Altura',
    'Ajuda',
    'Trabalho de casa',
    'Mel',
    'Esperança',
    'Hospital',
    'Hotel',
    'Hora',
    'Casa',
    'Marido',
    'Gelo',
    'Sorvete',
    'Idea',
    'Imaginação',
    'Informação',
    'Inseto',
    'Jaqueta',
    'Geléia',
    'Trabalho',
    'Suco',
    'Chave',
    'Teclado',
    'Chaveiro',
    'Criança',
    'Cozinha',
    'Faca',
    'Conhecimento',
    'Senhora/ Dama',
    'Terra (propriedade)',
    'Língua/Linguagem',
    'Lei',
    'Advogado',
    'Liderança',
    'Esquerda',
    'Perna',
    'Limão',
    'Limonada',
    'Carta',
    'Alface',
    'Biblioteca',
    'Vida',
    'Luz',
    'Fila',
    'Lábios',
    'Aparência',
    'Amor',
    'Almoço',
    'Revista',
    'Correio',
    'Correio (profissional)',
    'Shopping',
    'Gerente',
    'Mercado',
    'Marketing',
    'Casamento',
    'Material',
    'Metemática',
    'Carne',
    'Reunião',
    'Memória',
    'Homem',
    'Meia-noite',
    'Leite',
    'Mente',
    'Minuto',
    'Espelho',
    'Erro',
    'Mãe',
    'Momento',
    'Segunda-feira',
    'Dinheiro',
    'Lua',
    'Manhã',
    'Mãe',
    'Rato',
    'Boca',
    'Filme',
    'Música',
    'Nome',
    'Natureza',
    'Necessidade',
    'Bairro',
    'Sobrinho',
    'Jornal',
    'Sobrinha',
    'Noite',
    'Norte',
    'Nariz',
    'Caderno',
    'Número',
    'Enfermeira',
    'Objeto',
    'Escritório',
    'Pessoa que trabalha em escritório',
    'Opinião',
    'Laranja',
    'Outro',
    'Página',
    'Pintura',
    'Calças',
    'Papel',
    'Pais',
    'Parque',
    'Parte',
    'Parceiro',
    'Paixão',
    'Passado',
    'Macarrão',
    'Caminho',
    'Paz',
    'Caneta',
    'Lápis',
    'Pessoas',
    'Pimenta',
    'Período/ Ponto final/Menstruação',
    'Pessoa',
    'Foto',
    'Piano',
    'Fotografia/ Retrato',
    'Torta',
    'Abacaxi',
    'Pizza',
    'Lugar',
    'Planta',
    'Prato',
    'Jogador',
    'Poema',
    'Poeta',
    'Ponto',
    'Policial',
    'Porco',
    'Batata',
    'Poder/ Energia',
    'Prática',
    'Presente',
    'Presidente',
    'Preço',
    'Problema',
    'Professor de faculdade',
    'Projeto',
    'Público',
    'Porpósito',
    'Qualidade',
    'Coelho',
    'Corrida',
    'Radio',
    'Leitor',
    'Razão',
    'Receita',
    'Gravação/ Recorde',
    'Reflexo',
    'Geladeira',
    'Relação',
    'Pesquisa',
    'Restaurante',
    'Reunião',
    'Arroz',
    'Direita',
    'Anéis',
    'Risco',
    'Rio',
    'Estrada',
    'Pedra',
    'Romance',
    'Telhado/ Teto',
    'Quarto',
    'Regra',
    'Corrida',
    'Salada',
    'Sal',
    'Sábado',
    'Escola',
    'Ciência',
    'Tela',
    'Mar',
    'Estação do ano',
    'Secretária',
    'Sentido',
    'Serviço',
    'Prateleira',
    'Camisa',
    'Sapatos',
    'Show',
    'Lado',
    'Cantor',
    'Senhor',
    'Irmã',
    'Pele',
    'Saia',
    'Céu',
    'Celular',
    'Tênis',
    'Sabonete/Sabão',
    'Sociedade',
    'Sofá',
    'Refrigerante',
    'Software',
    'Solução',
    'Filho',
    'Canção',
    'Sopa',
    'Sul',
    'Espaço',
    'Palestrante/ Caixa de som',
    'Discurso',
    'Colher',
    'Primavera',
    'Funcionário',
    'Palco',
    'Estrela',
    'Estação',
    'Ações de empresa (dinheiro)',
    'Armazém',
    'Estória',
    'Estratégia',
    'Morango',
    'Rua',
    'Estresse',
    'Estudante',
    'Estilo',
    'Sujeito',
    'Metrô',
    'Açúcar',
    'Verão',
    'Sol',
    'Domingo',
    'Suporte',
    'Natação',
    'Simpatia',
    'Camiseta',
    'Mesa',
    'Conto',
    'Conversa',
    'Tarefa',
    'Chá',
    'Professor',
    'Time',
    'Tecnologia',
    'Adolescente',
    'Dentes',
    'Telefone',
    'Televisão',
    'Tênis',
    'Teste',
    'Texto',
    'Agradecimento',
    'Teatro',
    'Teoria',
    'Coisa',
    'Pensamento',
    'Quinta-feira',
    'Tempo',
    'Torrada/ Brinde',
    'Hoje',
    'Amanhã',
    'Língua (parte do corpo)',
    'Ferramenta',
    'Tópico',
    'Toque',
    'Cidade',
    'Trem',
    'Transporte',
    'Viagem',
    'Problema',
    'Calças',
    'Caminhão',
    'Verdade',
    'Terça-feira',
    'Tipo',
    'Guarda-chuva',
    'Tio',
    'Compreensão/ Entendimento',
    'Roupa íntima',
    'Universidade',
    'Vegetais',
    'Veículo',
    'Vídeo',
    'Visualizações',
    'Voz',
    'Volêi',
    'Volume',
    'Garçom',
    'Carteira',
    'Guarda-roupa',
    'Água',
    'Melão',
    'Caminho',
    'Clima',
    'Quarta-feira',
    'Semana',
    'Peso',
    'Oeste',
    'Esposa',
    'Janela',
    'Vinho',
    'Vencedor',
    'Inverno',
    'Mulher',
    'Madeira',
    'Palavra',
    'Trabalho',
    'Trabalhador',
    'Mundo',
    'Relógio de pulso',
    'Escritor',
    'Ano',
    'Ontem',
    'Juventude',
    'Futebol',
    'História',
    'Negócios',
    'Serviço',
    'Prédio',
    'Sorriso',
    'Felicidade',
  ];

  function getRandomInteger(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  function getWord(words, index) {
    return words.at(index);
  }

  function removeWord(words, word) {
    wordsCopy = [...words];
    return wordsCopy.filter(item => item !== word)
  }

  function getRandomWord(words) {
    const size = words.length;
    const randomInteger = getRandomInteger(1, size);
    return words.at(randomInteger);
  }

  function getMaskedWord(word) {
    console.log('word:', word);
    splittedWord = word.split("");
    if (getRandomInteger(0, 1)) {
      const w = splittedWord.map((character, index ) => {
        return index % 2 ? character : '_'; 
      })
      return w.join('');
    } else {
      const w = splittedWord.map((character, index ) => {
        return index % 2 ? '_' : character; 
      })
      return w.join('');
    }
  }

  function showTranslation(element, translation) {
    element.innerText = translation.toLowerCase();
  }

  function showWord(element, word) {    
    element.innerText = getMaskedWord(word.toLowerCase());
  }

  function showCounter(element, counter) {
    element.innerText = counter;
  }

  function showScore(element, score) {
    element.innerText = score;
  }

  function clearAndFocusElement(element) {
    element.value = "";
    element.focus();
  }

  function calculateScore(score, word, answer) {
    if (word.toLowerCase().trim() == answer.toLowerCase().trim()) {
      return score + 1;
    } 
    return score;
  }

  function main() {
    const wordElement = document.getElementById("word");
    const translationElement = document.getElementById("translation");
    const counterElement = document.getElementById("counter");
    const scoreElement = document.getElementById("score");
    const answerElement = document.getElementById("answer");

    const btnCheck = document.getElementById("btn-check");

    let counter = 0;
    let score = 0;

    const randomInteger = getRandomInteger(0, words.length - 1);
    // console.log('randomInteger:', randomInteger);
    let word = getWord(words, randomInteger);
    let translation = getWord(translatedWords, randomInteger);

    showWord(wordElement, word);     
    showTranslation(translationElement, translation) ;

    showScore(scoreElement, score);
    showCounter(counterElement, counter);
    clearAndFocusElement(answerElement);

    btnCheck.onclick = function () {
      counter++;
      const answer = answerElement.value;
      const newScore = calculateScore(score, word, answer);

      if (newScore > score) {
        // words = removeWord(words, word);
        // translatedWords = removeWord(translatedWords, translation);
      }
      // console.log('words.length:', words.length);
      // console.log('translatedWords.length', translatedWords.length)        
      score = newScore;

      const randomInteger = getRandomInteger(0, words.length - 1);
      // console.log('randomInteger:', randomInteger);
      word = getWord(words, randomInteger);
      translation = getWord(translatedWords, randomInteger);

      showWord(wordElement, word);      
      showTranslation(translationElement, translation);
      showScore(scoreElement, score);
      showCounter(counterElement, counter);
      clearAndFocusElement(answerElement);
    }
  }

  main();
}

